-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM(
    SELECT a.ANIMAL_ID, a.NAME
    FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
    ON a.ANIMAL_ID = b.ANIMAL_ID
    ORDER BY (b.DATETIME - a.DATETIME) DESC
)
WHERE ROWNUM < 3;