-- 코드를 입력하세요
SELECT B.TIME AS HOUR, NVL(COUNT(A.ANIMAL_ID), 0) AS COUNT
FROM ANIMAL_OUTS A 
RIGHT OUTER JOIN (SELECT LEVEL-1 TIME FROM DUAL CONNECT BY LEVEL <= 24) B
ON B.TIME = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24'))
GROUP BY B.TIME
ORDER BY 1;