-- 코드를 입력하세요
SELECT DISTINCT(B.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단' AND TO_CHAR(B.START_DATE, 'MM') = '10'
ORDER BY CAR_ID DESC;